name: Build
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  DEBUG: 1

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux64
          - linux32
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libc6-dev-i386
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86-x86_64
          path: |
            build/linux_x86/liblua_pluginscript.so
            build/linux_x86_64/liblua_pluginscript.so

  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - mingw-windows32
          - mingw-windows64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libc6-dev-i386 gcc-mingw-w64
      - name: Build artifact
        run: make ${{ matrix.target }}
        env:
          CC: gcc
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86-x86_64
          path: |
            build/windows_x86/lua51.dll
            build/windows_x86/lua_pluginscript.dll
            build/windows_x86_64/lua51.dll
            build/windows_x86_64/lua_pluginscript.dll

  build_osx_ios:
    name: Build OSX/iOS
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - osx64
          - ios64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build artifact
        run: make ${{ matrix.target }}
        env:
          LUA_BIN: lua5.1
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: osx-ios-arm64-x86_64
          path: |
            build/osx_arm64_x86_64/lua_pluginscript.dylib
            build/ios_arm64/lua_pluginscript.dylib
            build/ios_simulator_arm64_x86_64/lua_pluginscript.dylib

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - android-armv7a
          - android-aarch64
          - android-x86
          - android-x86_64
    env:
      ANDROID_NDK_VERSION: 21.4.7075529
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libc6-dev-i386
      - name: Setup NDK
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-armv7a-aarch64-x86-x86_64
          path: |
            build/android_armv7a/liblua_pluginscript.so
            build/android_aarch64/liblua_pluginscript.so
            build/android_x86/liblua_pluginscript.so
            build/android_x86_64/liblua_pluginscript.so

  build_distribution_zip:
    name: Build distribution zip
    needs: [build_linux, build_windows, build_osx_ios, build_android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Copy artifacts to build folder
        run: cp -r ${{ steps.download.outputs.download-path }}/*/* build
      - name: Make distribution
        run: make dist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lua_pluginscript
          path: |
            build/LICENSE
            build/addons/godot-lua-pluginscript/**

